"""empty message

Revision ID: 4b2a817ed481
Revises: None
Create Date: 2015-10-18 18:36:07.308856

"""

# revision identifiers, used by Alembic.
revision = '4b2a817ed481'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishwasher_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_clean', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishwasher_state')
    ### end Alembic commands ###
